create sequence hibernate_sequence start with 1 increment by 1;

create table user_roles (user_email varchar(250) not null, roles varchar(250));
create table users (email varchar(250) not null, firstname varchar(125) not null, middle_name varchar(50), surename varchar(125) not null, address varchar(150) not null, postal_code varchar(150) not null, password varchar(250) not null, enabled boolean not null, primary key (email));
create table purchase (id bigint generated by default as identity, booked_date date not null, user_email varchar(255) not null, trip_id bigint not null, primary key (id));
create table trip (id bigint generated by default as identity, title varchar(250) not null, description varchar(500) not null, cost integer not null, location varchar(150) not null, departure_date date not null, return_date date not null,  primary key (id));

alter table users add constraint UK_46ccwnsi9409t36lurvtyljak unique (email);
alter table user_roles add constraint FKs9rxtuttxq2ln7mtp37s4clce foreign key (user_email) references users;
alter table purchase add constraint FKlqrv1aj0pon999jbi5esfpe4k foreign key (user_email) references users;
alter table purchase add constraint FKlqrv1aj0pon999jbi5esfkdjf foreign key (trip_id) references Trip;

