create sequence hibernate_sequence start with 1 increment by 1;

create table user_roles (user_email varchar(255) not null, roles varchar(255));
create table users (email varchar(255) not null, firstname varchar(50) not null, middle_name varchar(50), surename varchar(50) not null, password varchar(255) not null, address varchar(128) not null, postal_code varchar(124) not null, enabled boolean not null, primary key (email));
create table purchase (id bigint generated by default as identity, booked_date date not null, user_email varchar(255) not null, primary key (id));
/*create table trip (id bigint generated by default as identity, title varchar(255) not null, description varchar(255), cost integer not null, location varchar(128) not null, departureDate varchar(128) not null, returnDate varchar(128) not null, primary key (id))
*/
/*alter table users add constraint UK_46ccwnsi9409t36lurvtyljak unique (email);*/
alter table user_roles add constraint FKs9rxtuttxq2ln7mtp37s4clce foreign key (user_email) references users;
alter table purchase add constraint FKlqrv1aj0pon999jbi5esfpe4k foreign key (user_email) references users;
/*alter table trip add constraint FKwqtq0m711iiym2m781dqr6n4 foreign key (purchase_id) references purchase;*/

